[AccessTransformers]
;BlueprintReadWrite=(Class="/Script/FactoryGame.FGCrabHatcher", Property="ItemToDrop")
BlueprintReadWrite=(Class="/Script/FactoryGame.FGCreature", Property="mItemToDrop")
BlueprintReadWrite=(Class="/Script/FactoryGame.FGCreature", Property="mDespawnDistance")
;