[AccessTransformers]
BlueprintReadWrite=(Class="/Script/FactoryGame.FGProductionIndicatorInstanceComponent", Property="mStateNoneData")
BlueprintReadWrite=(Class="/Script/FactoryGame.FGProductionIndicatorInstanceComponent", Property="mStateActiveData")
BlueprintReadWrite=(Class="/Script/FactoryGame.FGProductionIndicatorInstanceComponent", Property="mStateActiveWithCrystalData")
BlueprintReadWrite=(Class="/Script/FactoryGame.FGProductionIndicatorInstanceComponent", Property="mStateErrorData")
BlueprintReadWrite=(Class="/Script/FactoryGame.FGProductionIndicatorInstanceComponent", Property="mStateStandbyData")
BlueprintType=(Struct="/Script/FactoryGame.FGIndicatorReaction")
BlueprintReadWrite=(Class="/Script/FactoryGame.FGIndicatorReaction", Property="FlashingPattern")
BlueprintReadWrite=(Class="/Script/FactoryGame.FGIndicatorReaction", Property="mColor")
;

